name: molingo
channels:
  - bottler
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.9.1
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - chumpy=0.70
  - colorama=0.4.6
  - dataclasses=0.8
  - dav1d=1.2.1
  - decorator=5.2.1
  - expat=2.7.1
  - ffmpeg=7.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.10
  - fvcore=0.1.5.post20221221
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.9
  - graphite2=1.3.14
  - harfbuzz=12.1.0
  - icu=75.1
  - idna=3.7
  - imageio=2.37.0
  - imageio-ffmpeg=0.6.0
  - intel-openmp=2023.0.0
  - iopath=0.1.10
  - jinja2=3.1.6
  - jpeg=9e
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libass=0.17.3
  - libavif=1.1.1
  - libavif16=1.1.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.22
  - libdrm=2.4.125
  - libegl=1.7.0
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.86.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libopenvino=2024.4.0
  - libopenvino-auto-batch-plugin=2024.4.0
  - libopenvino-auto-plugin=2024.4.0
  - libopenvino-hetero-plugin=2024.4.0
  - libopenvino-intel-cpu-plugin=2024.4.0
  - libopenvino-intel-gpu-plugin=2024.4.0
  - libopenvino-intel-npu-plugin=2024.4.0
  - libopenvino-ir-frontend=2024.4.0
  - libopenvino-onnx-frontend=2024.4.0
  - libopenvino-paddle-frontend=2024.4.0
  - libopenvino-pytorch-frontend=2024.4.0
  - libopenvino-tensorflow-frontend=2024.4.0
  - libopenvino-tensorflow-lite-frontend=2024.4.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.50
  - libprotobuf=4.25.3
  - libsqlite=3.46.0
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.14.1
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - moviepy=1.0.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.9.1
  - networkx=3.4
  - numpy=1.23.5
  - nvidiacub=1.10.0
  - ocl-icd=2.3.2
  - openh264=2.4.1
  - openjpeg=2.5.0
  - openssl=3.5.4
  - p11-kit=0.24.1
  - packaging=25.0
  - pacmap=0.8.0
  - pcre2=10.46
  - pillow=11.0.0
  - pixman=0.46.4
  - pooch=1.8.2
  - portalocker=3.2.0
  - proglog=0.1.10
  - pthread-stubs=0.3
  - pugixml=1.14
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.10.13
  - python-annoy=1.17.3
  - python_abi=3.10
  - pyyaml=6.0.2
  - rav1e=0.6.6
  - readline=8.2
  - requests=2.32.4
  - scipy=1.10.1
  - six=1.17.0
  - snappy=1.2.2
  - sqlite=3.32.3
  - svt-av1=2.2.1
  - tabulate=0.9.0
  - tbb=2021.13.0
  - termcolor=3.1.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tqdm=4.67.1
  - urllib3=2.5.0
  - wayland=1.24.0
  - wayland-protocols=1.45
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.12
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xorgproto=2024.1
  - xorg-xproto=7.0.31
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yacs=0.1.8
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.9.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - blis==1.3.0
      - catalogue==2.0.10
      - click==8.2.1
      - cloudpathlib==0.23.0
      - cmake==4.1.2
      - confection==0.1.5
      - contourpy==1.3.2
      - cupy-cuda12x==13.5.1
      - cycler==0.12.1
      - cymem==2.0.11
      - diffusers==0.34.0
      - dotmap==1.3.30
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - fastrlock==0.8.3
      - filelock==3.20.0
      - fonttools==4.59.0
      - freetype-py==2.5.1
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h5py==3.15.1
      - hf-xet==1.1.5
      - huggingface-hub==0.34.2
      - hydra-core==0.11.3
      - importlib-metadata==8.7.0
      - jaxtyping==0.3.2
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - langcodes==3.5.0
      - language-data==1.3.0
      - lightning-utilities==0.15.0
      - llvmlite==0.44.0
      - lmdb==1.7.5
      - loguru==0.7.3
      - marisa-trie==1.3.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.5
      - mdurl==0.1.2
      - msgpack==1.1.2
      - msgpack-numpy==0.4.8
      - multidict==6.6.3
      - murmurhash==1.0.13
      - narwhals==2.0.1
      - ninja==1.13.0
      - nltk==3.9.1
      - numba==0.61.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.1.1
      - openai-clip==1.0.1
      - opencv-python==4.12.0.88
      - orjson==3.11.1
      - pandas==2.3.1
      - pathspec==0.12.1
      - pip==25.3
      - platformdirs==4.3.8
      - plotly==6.2.0
      - pot==0.9.5
      - preshed==3.0.10
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyglet==2.1.8
      - pygments==2.19.2
      - pyopengl==3.1.0
      - pyparsing==3.2.3
      - pyrender==0.1.45
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.5.2
      - pytz==2025.2
      - rectified-flow==1.0.1
      - regex==2024.11.6
      - rich==14.2.0
      - safetensors==0.5.3
      - scikit-build-core==0.11.6
      - scikit-learn==1.7.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.34.1
      - setuptools==80.9.0
      - shapely==2.1.1
      - shellingham==1.5.4
      - smart-open==7.4.1
      - smmap==5.0.2
      - smplx==0.1.28
      - soupsieve==2.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - sympy==1.14.0
      - timm==1.0.19
      - tokenizers==0.21.2
      - tomli==2.3.0
      - transformers==4.54.0
      - trimesh==4.7.4
      - triton==3.5.0
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - wadler-lindig==0.1.7
      - wandb==0.21.0
      - wasabi==1.1.3
      - wcwidth==0.2.13
      - weasel==0.4.1
      - wrapt==2.0.0
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /home/hynann/apps/anaconda3/envs/molingo
